# Generated by Django 5.0.7 on 2024-07-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductorname', models.CharField(max_length=100)),
                ('dniconductor', models.IntegerField(max_length=100)),
                ('patentevehiculo', models.CharField(max_length=100)),
                ('modelovehiculo', models.CharField(max_length=100)),
                ('capacidadvehiculo', models.CharField(max_length=100)),
                ('estadovehiculo', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
