# Generated by Django 5.0.7 on 2024-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='dniconductor',
            field=models.IntegerField(),
        ),
    ]
